services:
  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./static_files:/usr/share/nginx/html/static_files"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app